# Generated by Django 5.1.4 on 2025-03-07 14:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_background',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, validators=[accounts.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_emoji',
            field=models.CharField(default='👤', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
