# Generated by Django 5.1.4 on 2025-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresetcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/', verbose_name='Avatar Image'),
        ),
    ]
