# Generated by Django 5.1.4 on 2025-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar_background_customuser_avatar_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_emoji',
            field=models.CharField(default='👤', max_length=3),
        ),
    ]
