# Generated by Django 5.1.4 on 2025-08-29 14:04

import tools.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_background',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, validators=[tools.validators.validate_hex_color], verbose_name='Avatar Background'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_emoji',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Avatar Emoji'),
        ),
    ]
