# Generated by Django 5.1.4 on 2025-06-29 15:29

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0002_workspace_currency_workspacerole_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('key', models.CharField(max_length=10, verbose_name='Key')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Is Billable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('avatar_background', models.CharField(blank=True, default='#ffffff', max_length=7, null=True, validators=[accounts.models.validate_hex_color], verbose_name='Avatar Background')),
                ('avatar_emoji', models.CharField(default='🚀', max_length=3, verbose_name='Avatar Emoji')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='project/', verbose_name='Avatar Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workspace', to='workspace.workspace', verbose_name='Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price'), ('subscription', 'Subscription'), ('per_task', 'Per Task'), ('non_billable', 'Non-Billable')], default='fixed', max_length=20, verbose_name='Type')),
                ('limit', models.DecimalField(decimal_places=2, help_text='Maximum budget or spending limit. Use 0.00 if unlimited.', max_digits=10, verbose_name='Billing Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='project.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quote_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('invoice', 'Invoice Issued'), ('refund', 'Refund')], default='invoice', max_length=20, verbose_name='Quote type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Use negative values for withdrawals if needed', max_digits=10, verbose_name='Transaction Amount')),
                ('proof', models.FileField(blank=True, null=True, upload_to='billing/proofs/', verbose_name='Proof of Transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('project_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='project.projectbilling', verbose_name='Project billing')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
