# Generated by Django 5.1.4 on 2025-06-20 19:22

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='workspacerole',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Role Settings'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='avatar_background',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, validators=[accounts.models.validate_hex_color], verbose_name='Avatar Background'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='avatar_emoji',
            field=models.CharField(default='🚀', max_length=3, verbose_name='Avatar Emoji'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='workspaces/', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='workspacerole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workspacerole',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Role name'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='workspace.workspacerole', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='workspace.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Member',
                'verbose_name_plural': 'Workspace Members',
                'unique_together': {('user', 'workspace')},
            },
        ),
        migrations.DeleteModel(
            name='WorkspaceMembership',
        ),
    ]
