# Generated by Django 5.1.4 on 2025-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
