# Generated by Django 5.1.4 on 2025-03-13 19:17

import workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_is_active_workspacemembership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='avatar_background',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, validators=[workspace.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='workspace',
            name='avatar_emoji',
            field=models.CharField(default='🚀', max_length=3),
        ),
        migrations.AddField(
            model_name='workspace',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='workspaces/'),
        ),
    ]
